<?php

declare(strict_types=1);

namespace App\Service\Gateways;

use App\Service\Gateways\Abstractions\AbstractGateway;

class WitWallet extends AbstractGateway
{
    //Storing your funds with witty charm.
    //Charms generated by chatGPT

    public function execute(): string
    {
        $jokes = [
            'Clever Compliment: "Are you a magician? Because whenever I look at you, everyone else disappears."',
            'Quick Comeback: When someone says, "Youre late!" You reply, "Better late than ugly."',
            'Playful Teasing: "You must be made of copper and tellurium because youre Cu-Te."',
            'Double Entendre: "I used to play piano by ear, but now I use my hands."',
            'Sarcasm: When someone asks if youre free, you say, "Im as free as a bird, as long as that bird has Wi-Fi."',
            'Punny Joke: "Im reading a book on anti-gravity. Its impossible to put down!"',
            'Self-Deprecating Humor: "Im not saying Im Wonder Woman; Im just saying no one has ever seen me and Wonder Woman in the same room together."',
            'Witty Observation: "Life is like a bicycle. To keep your balance, you must keep moving."',
            'Wordplay: "I used to be a baker, but I couldnt make enough dough."',
            'Subtle Flattery: "You have the most contagious smile. I bet you could make even a lemon laugh."',
        ];

        return $jokes[array_rand($jokes)];
    }
}
